'use client';

import React, { useState } from 'react';
import { ForensicCase } from '@/types/forensics';
import {
  FileText,
  Download,
  Share2,
  Printer,
  CheckCircle2,
  ArrowUp,
  Shield,
  ChevronDown,
  ChevronUp,
} from 'lucide-react';

interface ForensicReportProps {
  currentCase: ForensicCase;
  onClose?: () => void;
}

export const ForensicReport: React.FC<ForensicReportProps> = ({ currentCase, onClose }) => {
  const [copied, setCopied] = useState<boolean>(false);
  const [showFullReport, setShowFullReport] = useState<boolean>(false);

  const handlePrint = () => {
    window.print();
  };

  const handleExport = () => {
    const dataStr = 'data:text/json;charset=utf-8,' + encodeURIComponent(JSON.stringify(currentCase, null, 2));
    const a = document.createElement('a');
    a.href = dataStr;
    a.download = `PIXORA_${currentCase.caseId}_REPORT.json`;
    document.body.appendChild(a);
    a.click();
    a.remove();
  };

  const handleShare = () => {
    navigator.clipboard.writeText(
      `https://pixora.forensics/dockets/${currentCase.caseId}?hash=${currentCase.sha256Hash.substring(0, 16)}`
    );
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  // Technical sections for the expanded full report (RULE 9: TRACEABILITY)
  const fullTechnicalSections = [
    {
      num: '01',
      title: 'FINAL ASSESSMENT',
      content: `${currentCase.assessment.outcome} — ${currentCase.assessment.subtitle || 'Decision generated by IMAGE-TRACE engine.'}`,
      techNote: `Decision state: ${currentCase.assessment.outcome} | Eligibility: ${currentCase.assessment.eligibility || 'N/A'}.`,
    },
    {
      num: '02',
      title: 'EVIDENCE SUFFICIENCY',
      content: `Sufficiency rating: ${currentCase.assessment.sufficiency || currentCase.evaluation.sufficiency}. Eligibility: ${currentCase.assessment.eligibility || currentCase.evaluation.eligibility}.`,
      techNote: `Trace ID: ${currentCase.caseId} | SHA-256: ${currentCase.sha256Hash}`,
    },
    {
      num: '03',
      title: 'PIXEL FORENSICS',
      content: `${currentCase.pixelForensics.statusLabel} — ${currentCase.pixelForensics.technique}.`,
      techNote: currentCase.pixelForensics.limitations || 'Compression-domain measurement.',
    },
    {
      num: '04',
      title: 'METADATA',
      content: `${currentCase.metadata.software} — ${currentCase.metadata.advisory}`,
      techNote: `Format: ${currentCase.fileFormat} | Resolution: ${currentCase.metadata.dimensions}`,
    },
    {
      num: '05',
      title: 'PROVENANCE',
      content: `${currentCase.provenance.credentialStatus} — ${currentCase.provenance.advisory}`,
      techNote: 'Cryptographic provenance verification status.',
    },
    {
      num: '06',
      title: 'EVIDENCE RELATIONSHIPS',
      content: currentCase.relationships.length > 0 
        ? currentCase.relationships.map((r) => `${r.label}: ${r.conflictReason}`).join(' | ')
        : 'No cross-signal relationship pairs established.',
      techNote: `Total relationships evaluated: ${currentCase.relationships.length}`,
    },
    {
      num: '07',
      title: 'MISSING EVIDENCE / BOUNDARIES',
      content: currentCase.assessment.whatCannotBeEstablished.join(' · ') || (currentCase.assessment.missingEvidence?.join(' · ') || 'None logged'),
      techNote: 'Forensic boundary limitations established by decision maker.',
    },
  ];

  return (
    <div id="report" className="rounded-2xl bg-white border border-[#D6D0C5] p-6 sm:p-10 shadow-xs space-y-6 font-sans">
      {/* Header Toolbar */}
      <div className="flex flex-wrap items-center justify-between gap-4 pb-4 border-b border-[#D6D0C5] no-print">
        <div className="flex items-center gap-2.5">
          <div className="w-8 h-8 rounded-lg bg-[#3155FF]/10 text-[#3155FF] flex items-center justify-center border border-[#3155FF]/20">
            <FileText className="w-4 h-4" />
          </div>
          <div>
            <div className="text-[10px] font-mono font-bold uppercase text-[#77736C]">
              OFFICIAL REPORT PREVIEW
            </div>
            <div className="text-sm font-bold text-[#111111]">
              PIXORA FORENSIC ASSESSMENT REPORT
            </div>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="flex flex-wrap items-center gap-2">
          <button
            onClick={handleExport}
            className="flex items-center gap-1.5 px-3.5 py-1.5 rounded-xl bg-[#3155FF] hover:bg-[#2345E5] text-white text-xs font-semibold transition-all shadow-md shadow-[#3155FF]/20 active:scale-[0.98]"
          >
            <Download className="w-3.5 h-3.5" />
            <span>EXPORT REPORT</span>
          </button>

          <button
            onClick={handlePrint}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-[#FAF8F5] hover:bg-[#F4F0E8] border border-[#D6D0C5] text-[#111111] text-xs font-medium transition-colors"
          >
            <Printer className="w-3.5 h-3.5" />
            <span className="hidden sm:inline">PRINT</span>
          </button>

          <button
            onClick={handleShare}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-[#FAF8F5] hover:bg-[#F4F0E8] border border-[#D6D0C5] text-[#111111] text-xs font-medium transition-colors"
          >
            {copied ? (
              <>
                <CheckCircle2 className="w-3.5 h-3.5 text-[#2B4E08]" />
                <span className="text-[#2B4E08]">COPIED</span>
              </>
            ) : (
              <>
                <Share2 className="w-3.5 h-3.5 text-[#77736C]" />
                <span className="hidden sm:inline">SHARE</span>
              </>
            )}
          </button>

          {onClose && (
            <button
              onClick={onClose}
              className="flex items-center gap-1 px-2.5 py-1.5 rounded-xl bg-[#FAF8F5] hover:bg-[#F4F0E8] border border-[#D6D0C5] text-[#77736C] hover:text-[#111111] transition-colors text-xs"
            >
              <ArrowUp className="w-3.5 h-3.5" />
              <span>TOP</span>
            </button>
          )}
        </div>
      </div>

      {/* =========================================================================
          SECTION 19: CLEAN PROFESSIONAL REPORT PREVIEW
          Top:
          PIXORA / FORENSIC ASSESSMENT REPORT
          Case: PX-2026-00142
          Result: INCONCLUSIVE
         ========================================================================= */}
      <div className="p-6 rounded-xl bg-[#FAF8F5] border border-[#D6D0C5] space-y-5">
        <div className="flex flex-wrap items-start justify-between gap-4 pb-4 border-b border-[#E7E2D8]">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <Shield className="w-4 h-4 text-[#3155FF]" />
              <span className="font-mono text-xs font-bold text-[#111111] tracking-wider uppercase">
                PIXORA FORENSIC ASSESSMENT REPORT
              </span>
            </div>
            <div className="text-xs text-[#77736C] font-mono">
              Case: <strong className="text-[#111111]">{currentCase.caseId}</strong> • Date: 2026-10-07
            </div>
          </div>

          <div className="text-right">
            <div className="text-[10px] font-mono uppercase font-semibold text-[#77736C]">RESULT</div>
            <div className="text-xl font-bold font-mono text-[#9C4E00]">
              {currentCase.assessment.outcome}
            </div>
          </div>
        </div>

        {/* 1. EXECUTIVE FINDING (2-3 sentences) */}
        <div className="space-y-1.5">
          <div className="text-[11px] font-mono uppercase font-bold text-[#77736C]">
            EXECUTIVE FINDING
          </div>
          <p className="text-sm text-[#111111] leading-relaxed">
            Examination of {currentCase.originalFileName} identified localized pixel inconsistencies on Region 03
            consistent with image splicing, corroborated by secondary Photoshop editing metadata.
            However, authenticated camera provenance credentials assert that the baseline image was authentically captured,
            precluding an automated conclusive verdict without manual source corroboration.
          </p>
        </div>

        {/* 2. EVIDENCE SUMMARY */}
        <div className="space-y-2 pt-2 border-t border-[#E7E2D8]">
          <div className="text-[11px] font-mono uppercase font-bold text-[#77736C]">
            EVIDENCE SUMMARY
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-xs">
            <div className="p-2.5 rounded-lg bg-white border border-[#D6D0C5] flex items-center justify-between">
              <span className="text-[#111111] font-mono font-medium">Pixels</span>
              <span className="px-2 py-0.5 rounded bg-[#B7E43A]/25 text-[#2B4E08] font-mono text-[10px] font-bold border border-[#B7E43A]">
                SUPPORTS
              </span>
            </div>

            <div className="p-2.5 rounded-lg bg-white border border-[#D6D0C5] flex items-center justify-between">
              <span className="text-[#111111] font-mono font-medium">Metadata</span>
              <span className="px-2 py-0.5 rounded bg-[#B7E43A]/25 text-[#2B4E08] font-mono text-[10px] font-bold border border-[#B7E43A]">
                SUPPORTS
              </span>
            </div>

            <div className="p-2.5 rounded-lg bg-white border border-[#D6D0C5] flex items-center justify-between">
              <span className="text-[#111111] font-mono font-medium">Provenance</span>
              <span className="px-2 py-0.5 rounded bg-[#FEECEC] text-[#F04444] font-mono text-[10px] font-bold border border-[#F04444]/40">
                CONFLICTS
              </span>
            </div>

            <div className="p-2.5 rounded-lg bg-white border border-[#D6D0C5] flex items-center justify-between">
              <span className="text-[#111111] font-mono font-medium">Synthetic analysis</span>
              <span className="px-2 py-0.5 rounded bg-[#B7E43A]/25 text-[#2B4E08] font-mono text-[10px] font-bold border border-[#B7E43A]">
                CONSISTENT
              </span>
            </div>
          </div>
        </div>

        {/* 3. ASSESSMENT */}
        <div className="space-y-1.5 pt-2 border-t border-[#E7E2D8]">
          <div className="text-[11px] font-mono uppercase font-bold text-[#77736C]">
            ASSESSMENT
          </div>
          <p className="text-xs sm:text-sm text-[#111111] leading-relaxed">
            The system cannot safely conclude because observed physical pixel signals contradict the certified cryptographic provenance credential.
            Drawing an automated verdict under contradictory signals violates forensic evidentiary integrity.
          </p>
        </div>

        {/* 4. RECOMMENDED ACTION */}
        <div className="space-y-1.5 pt-2 border-t border-[#E7E2D8]">
          <div className="text-[11px] font-mono uppercase font-bold text-[#77736C]">
            RECOMMENDED ACTION
          </div>
          <p className="text-xs sm:text-sm text-[#111111] font-medium leading-relaxed">
            Manual Review — Verify the original camera memory card or obtain independent corroborating copies before courtroom or editorial submission.
          </p>
        </div>
      </div>

      {/* =========================================================================
          SECTION 19 & 20: VIEW FULL REPORT (PROGRESSIVE DISCLOSURE)
          "The full technical report can contain detailed forensic information.
          The default report preview should NOT."
         ========================================================================= */}
      <div className="pt-2 flex flex-col items-start gap-3">
        <button
          onClick={() => setShowFullReport(!showFullReport)}
          className="flex items-center gap-1.5 text-xs font-sans font-bold text-[#3155FF] hover:underline"
        >
          <span>{showFullReport ? 'HIDE FULL TECHNICAL DOSSIER' : 'VIEW FULL REPORT →'}</span>
          {showFullReport ? <ChevronUp className="w-3.5 h-3.5" /> : <ChevronDown className="w-3.5 h-3.5" />}
        </button>

        {showFullReport && (
          <div className="w-full space-y-3 pt-3 border-t border-[#D6D0C5] animate-in fade-in duration-100">
            {fullTechnicalSections.map((sec) => (
              <div
                key={sec.num}
                className="p-4 rounded-xl border border-[#D6D0C5] bg-[#FAF8F5] space-y-1.5 text-xs"
              >
                <div className="flex items-center gap-2">
                  <span className="font-mono font-bold text-[#3155FF]">{sec.num}</span>
                  <span className="font-mono font-bold uppercase text-[#111111]">{sec.title}</span>
                </div>
                <p className="text-[#111111] pl-6 font-sans">{sec.content}</p>
                <div className="text-[11px] font-mono text-[#77736C] pl-6 pt-1 border-t border-[#E7E2D8] mt-1">
                  <strong className="text-[#3155FF]">TECHNICAL NOTE: </strong>
                  {sec.techNote}
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
};
